name: pocket-js-server

services:
  db:
    image: bitnami/postgresql:13.16.0
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    volumes:
      - dbdata:/bitnami/postgresql

  app:
    build:
      context: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3333:3333"
    depends_on:
      - db
    volumes:
      - .:/app
    entrypoint: ["sh", "-c", "chmod +x /app/scripts/init.sh && /app/scripts/init.sh"]

volumes:
  dbdata:
    driver: local

